name: bbhouse
description: Flutter版本 仿 贝壳找房
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # iOS style icons
  cupertino_icons: ^0.1.2

  # rxdart https://github.com/ReactiveX/rxdart
  rxdart: ^0.22.2
  # dio
  dio: ^2.1.6
  # cookie_jar
  cookie_jar: ^1.0.1
  # package_info
  package_info: ^0.4.0+6
  # device_info
  device_info: ^0.4.0+2
  # shared_preferences
  shared_preferences: ^0.5.3+4
  # path_provider
  path_provider: ^1.3.0
  # toast
  fluttertoast: ^3.1.1
  # log https://github.com/Leo0618/flog
  flog:
    git: https://github.com/Leo0618/flog.git
  # https://github.com/xuelongqy/flutter_easyrefresh
  flutter_easyrefresh: ^2.0.4
  # https://github.com/flutter/plugins/tree/master/packages/webview_flutter
  webview_flutter: ^0.3.14+1

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # use Material Icons font
  uses-material-design: true

  assets:
    # assets-generator-begin
    # assets/img/*
    - assets/img/bg_alert.png
    - assets/img/bg_splash.png
    - assets/img/empty.png
    - assets/img/homeActivity1.png
    - assets/img/homeActivity2.png
    - assets/img/homeershou1.png
    - assets/img/homeershou2.png
    - assets/img/homeershou3.png
    - assets/img/homeNews1.png
    - assets/img/homeNews2.png
    - assets/img/homeNews3.png
    - assets/img/homexin1.png
    - assets/img/homexin2.png
    - assets/img/homexin3.png
    - assets/img/homeZhuansu1.png
    - assets/img/homeZhuansu2.png
    - assets/img/hot_ic1.png
    - assets/img/hot_ic2.png
    - assets/img/hot_ic3.png
    - assets/img/house1.png
    - assets/img/house2.png
    - assets/img/house3.png
    - assets/img/house4.png
    - assets/img/house5.png
    - assets/img/house6.png
    - assets/img/icon_account_normal.png
    - assets/img/icon_account_selected.png
    - assets/img/icon_feedlist_normal.png
    - assets/img/icon_feedlist_selected.png
    - assets/img/icon_home_normal.png
    - assets/img/icon_home_selected.png
    - assets/img/icon_nav_location.png
    - assets/img/icon_news_normal.png
    - assets/img/icon_news_selected.png
    - assets/img/img_default_squar_large.png
    - assets/img/img_default_squar_small.png
    - assets/img/img_default_width.png
    - assets/img/slogan.png
    - assets/img/zhishu.png
    - assets/img/zhishu1.png
    - assets/img/zhishu2.png
    # assets-generator-end
    - assets/data_home.json


